//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura
    {
        public Asignatura()
        {
            this.Profesor = new HashSet<Profesor>();
            this.Estudiante = new HashSet<Estudiante>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Num_cred { get; set; }
        public Nullable<int> Nivel { get; set; }
    
        public virtual ICollection<Profesor> Profesor { get; set; }
        public virtual ICollection<Estudiante> Estudiante { get; set; }
    }
}
